[Tensor shape 변경/View Tensor]

In [39]:
#모듈 로딩
import numpy as np
import torch

In [40]:
#tensor 생성
dataTS=torch.arange(1,21)
print(dataTS, dataTS.ndim, dataTS.stride(), sep='\n')
print(f'is_contiguous(): {dataTS.is_contiguous()}')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)
is_contiguous(): True


In [41]:
#1차원 -> 2차원 형태 변경
dataTS2=dataTS.reshape((-1,5))
print(dataTS2, dataTS2.ndim, dataTS2.stride(), sep='\n')
print(f'is_contiguous(): {dataTS2.is_contiguous()}')


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
is_contiguous(): True


In [42]:
print(dataTS2.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [43]:
dataTS2[0][0]=77

In [44]:
dataTS,dataTS2

(tensor([77,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 tensor([[77,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

In [45]:
dataTS22=dataTS2.reshape((-1,2))
print(dataTS22, dataTS22.ndim, dataTS22.stride(), sep='\n')
print(f'is_contiguous(): {dataTS22.is_contiguous()}')


tensor([[77,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
is_contiguous(): True


In [49]:
dataTS22.T

tensor([[77,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]])

In [48]:
dataTS23=dataTS22.T
dataTS23.is_contiguous()

False

In [51]:
dataTS23.storage()

 77
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [54]:
#불연속적인 tensor -> 연속적인 tensor로 바꿔줌
dTS=dataTS23.contiguous()

In [55]:
dTS.storage()

 77
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [56]:
dTS.is_contiguous()

True