#### Tensor 이해
##### [생성]
- Torch.rand()

In [2]:
#모듈 로딩
import torch

In [9]:
#0<= n <1 범위의 임의의 숫자 1개 추출 w. rand
torch.manual_seed(1)

dataTS=torch.rand(3)
dataTS

tensor([0.7576, 0.2793, 0.4031])

In [10]:
dataTS=torch.rand(2,3)

dataTS

tensor([[0.7347, 0.0293, 0.7999],
        [0.3971, 0.7544, 0.5695]])

In [17]:
dataTS=torch.rand(1,2,3)

dataTS

tensor([[[0.1227, 0.5304, 0.4148],
         [0.7937, 0.2104, 0.0555]]])

rand(*size): 가변인자 ( 몇차원이 올지 모르니까 )

##### [생성]
- Torch.randn()

In [13]:
dataTS=torch.randn(3)
dataTS

tensor([ 0.5773, -1.7637,  0.2264])

In [14]:
dataTS=torch.randn(2,3)

dataTS

tensor([[-0.2355,  0.3019, -0.2770],
        [ 0.4771, -0.1103,  0.2913]])

In [16]:
dataTS=torch.randn(1,2,3)

dataTS

tensor([[[ 0.1889,  0.3040,  0.2830],
         [ 2.0379,  0.1633, -0.0177]]])

##### [생성]
- Torch.randint()

In [18]:
torch.randint(1,5,(3,5))

tensor([[4, 3, 2, 1, 3],
        [2, 4, 4, 3, 4],
        [2, 1, 4, 2, 2]])

In [19]:
#1d
torch.randint(1,46,(6,))

tensor([34, 17, 32,  7, 11,  6])

In [20]:
#2d
torch.randint(1,46,(4,6))

tensor([[43, 26, 29, 41, 36, 25],
        [20, 18, 16, 11, 24, 31],
        [23, 17, 30,  3, 30, 30],
        [44, 15, 38, 22, 25, 27]])