#### Tensor 이해

In [1]:
#모듈 로딩
import torch

- 타입 지정 Tensor 클래스 활용
    * 데이터 타입 설정 후 생성
    * 데이터 사이즈 설정한 Tensor 생성 시 사용
    * 데이터 자료형 변환한 Tensor 생성 시 사용

In [2]:
# 정수형 텐서 생성
data=[1.4,2.8,3.1]

In [4]:
#1byte 정수형 Tensor 생성
dataTS=torch.CharTensor(data)
dataTS

C:\Users\desktop\AppData\Local\Temp\ipykernel_17012\4291427910.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS=torch.CharTensor(data)


tensor([1, 2, 3], dtype=torch.int8)

In [5]:
dataTS1=torch.tensor(data,dtype=torch.int8)
dataTS1

C:\Users\desktop\AppData\Local\Temp\ipykernel_17012\973279340.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1=torch.tensor(data,dtype=torch.int8)


tensor([1, 2, 3], dtype=torch.int8)

In [6]:
#2bytes 정수형 Tensor 생성
dataTS=torch.ShortTensor(data)
dataTS

C:\Users\desktop\AppData\Local\Temp\ipykernel_17012\276748807.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS=torch.ShortTensor(data)


tensor([1, 2, 3], dtype=torch.int16)

In [7]:
dataTS1=torch.tensor(data,dtype=torch.int16)
dataTS1

C:\Users\desktop\AppData\Local\Temp\ipykernel_17012\1588047320.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  dataTS1=torch.tensor(data,dtype=torch.int16)


tensor([1, 2, 3], dtype=torch.int16)

In [8]:
#논리형 Tensor 생성
dataTS=torch.BoolTensor(data)
dataTS

tensor([True, True, True])

In [9]:
dataTS1=torch.tensor(data,dtype=torch.bool)
dataTS1

tensor([True, True, True])

In [10]:
data2=[0.,0.1,3.6]

In [11]:
dataTS=torch.BoolTensor(data2)
dataTS

tensor([False,  True,  True])

In [12]:
dataTS1=torch.tensor(data2,dtype=torch.bool)
dataTS1

tensor([False,  True,  True])

0만 False / 나머지는 다 True

In [13]:
#실수형 Tensor 생성
dataTS=torch.DoubleTensor(data)
dataTS

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)

In [14]:
dataTS1=torch.tensor(data,dtype=torch.float64)
dataTS1

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)

- Tensor 저장 및 실행 위치 설정
    * 속성 device 설정

In [15]:
device='cuda' if torch.cuda.is_available() else 'cpu'

In [16]:
device

'cpu'

In [17]:
dataTS1=torch.tensor(data,dtype=torch.float64,device=device)
dataTS1

tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)