#### [Tensor 변환]

[torch.as_tensor()]
- 동일 타입, 동일 디바이스를 가진 데이터가 존재하면 데이터 공유 => view
- 타입이 다르거나 디바이스가 다르면 데이터 복사(새로 생성) => copy
- view tensor 또는 copy tensor 반환

In [19]:
#모듈 로딩
import torch

- python list -> torch Tensor

In [20]:
data=list(range(1,10))

dataTS=torch.as_tensor(data,dtype=torch.int8)
dataTS, dataTS.shape, dataTS.ndim,dataTS.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [21]:
data [0]=100

In [22]:
data, dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy ndarray -> Tensor

In [23]:
import numpy as np

In [24]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [25]:
arrTs=torch.as_tensor(arr1)
arrTs

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
arr1[0]=77

In [27]:
arr1,arrTs

(array([77,  2,  3]), tensor([77,  2,  3], dtype=torch.int32))

In [28]:
arrTs[0]=99

In [29]:
arr1,arrTs

(array([99,  2,  3]), tensor([99,  2,  3], dtype=torch.int32))

- Numpy ndarray -> Tensor w. from_numpy()

In [31]:
arr1=np.array([5,7,9],dtype=np.float32)
print(arr1)
print(f'데이터 저장 메모리: {arr1.data}')
print(f'원소/요소 개수: {arr1.size}')
print(f'원소/요소 1개의 크기: {arr1.itemsize}')
print(f'데이터 타입: {arr1.dtype}')
print(f'데이터 방향: {arr1.strides}')

[5. 7. 9.]
데이터 저장 메모리: <memory at 0x000001DBCB133340>
원소/요소 개수: 3
원소/요소 1개의 크기: 4
데이터 타입: float32
데이터 방향: (4,)


In [32]:
arr1=np.array([[5,7,9],[1,2,3]],dtype=np.float16)
print(arr1)
print(f'데이터 저장 메모리: {arr1.data}')
print(f'원소/요소 개수: {arr1.size}')
print(f'원소/요소 1개의 크기: {arr1.itemsize}')
print(f'데이터 타입: {arr1.dtype}')
print(f'데이터 방향: {arr1.strides}')

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리: <memory at 0x000001DBCB09B930>
원소/요소 개수: 6
원소/요소 1개의 크기: 2
데이터 타입: float16
데이터 방향: (6, 2)


In [33]:
arr_ts = torch.from_numpy(arr1) 
arr_ts

tensor([[5., 7., 9.],
        [1., 2., 3.]], dtype=torch.float16)