[이미지 DRAWING]
- 이미지 객체 ndarray 준비 필요

In [1]:
import cv2
import numpy as np

In [2]:
#데이터 관련 변수 설정
dir_path='../image/'

In [25]:
#이미지 객체
bg_data=np.full((500,500,3),255)    # 255: white, 0: black

#이미지 파일 생성
bg_file=dir_path+'white_bg.jpg'
cv2.imwrite(bg_file,bg_data)

print(bg_data)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [26]:
#도화지 이미지 가져오기
white_bg=cv2.imread(bg_file)

white_bg.shape, white_bg.ndim

((500, 500, 3), 3)

In [21]:
#선그리기
                                    #B, G, R
cv2.line(white_bg,(50,50),(250,250),(255,0,0),5)    #종이, 시작점, 끝나는 지점, 선 색깔, 선 두께
cv2.line(white_bg,(100,50),(250,250),(0,255,0),5)    #종이, 시작점, 끝나는 지점, 선 색깔, 선 두께

cv2.imshow('DRAWING',white_bg)      #창 이름, 그림
cv2.waitKey()
cv2.destroyAllWindows()

In [30]:
#사각형 그리기
cv2.rectangle(white_bg,(50,50),(120,70),(0,255,255),-1)     #선 두께 자리에ㅔ '-1' 넣으면 사각형 안을 채워줌
cv2.imshow('DRAWING',white_bg)      
cv2.waitKey()
cv2.destroyAllWindows()