#### Tensor 이해
##### [생성]
- Tensor
    * pytorch에서 데이터를 저장하는 객체
    * 모델에서 입/출력 데이터 형태

[int]
- 1byte=8bit=256개 ( int8 / uint8 )
    * -128~127 / 0~255

- short: 16bit => -215~215-1 ( int16 / uint16 )
- int: 32bit ( int32 / uint32 )
- long int: 64bit ( int64 / uint64 )

- 기본 데이터 타입: 숫자, 글자 ( int, float, char, bool 등 )
    * 힙에 저장됨 ( 클래스 기반 객체 )
- 확장 데이터 타입: 여러 개의 기본 데이터 타입이 모여 하나의 데이터 타입 표현 ( string 등 ) => 클래스
    * 힙에 저장됨 ( 클래스 기반 객체 )

- float: 소수점 이하 자릿수
- double: float 소수점 2배

In [3]:
import torch

print(f' torch v.{torch.__version__}')

 torch v.2.4.1


In [4]:
#함수 기능: 텐서 속성 정보 출력 함수

def print_info(obj,obj_name):
    print(f'\n[{obj_name}]')
    print(f'shape: {obj.shape}')
    print(f'ndim: {obj.ndim}차원')
    print(f'dtype: {obj.dtype}')
    print(f'device: {obj.device}')
    print(f'data: \n{obj.data}')

[텐서 생성]
1. torch.tensor()

In [10]:
# 데이터 1개(스칼라)
dataTF=torch.tensor(10)
print_info(dataTF,'dataTF')

dataTF=torch.tensor(10,dtype=torch.uint8)
print_info(dataTF,'dataTF')


[dataTF]
shape: torch.Size([])
ndim: 0차원
dtype: torch.int64
device: cpu
data: 
10

[dataTF]
shape: torch.Size([])
ndim: 0차원
dtype: torch.uint8
device: cpu
data: 
10


In [7]:
dataTF=torch.Tensor(10)
print_info(dataTF,'dataTF')


[dataTF]
shape: torch.Size([10])
ndim: 1차원
dtype: torch.float32
device: cpu
data: 
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [9]:
# 데이터 1개(벡터)
dataTF=torch.tensor([10])
print_info(dataTF,'dataTF')


[dataTF]
shape: torch.Size([1])
ndim: 1차원
dtype: torch.int64
device: cpu
data: 
tensor([10])


In [12]:
# 데이터 1개(행렬)
dataTF=torch.tensor([[10]])
print_info(dataTF,'dataTF')

dataTF=torch.tensor([[10],[20]],dtype=torch.uint8)
print_info(dataTF,'dataTF')


[dataTF]
shape: torch.Size([1, 1])
ndim: 2차원
dtype: torch.int64
device: cpu
data: 
tensor([[10]])

[dataTF]
shape: torch.Size([2, 1])
ndim: 2차원
dtype: torch.uint8
device: cpu
data: 
tensor([[10],
        [20]], dtype=torch.uint8)


In [13]:
zten1=torch.zeros(2,5)

print_info(zten1,'zten1')


[zten1]
shape: torch.Size([2, 5])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [14]:
zten2=torch.zeros(3)

print_info(zten2,'zten2')


[zten2]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.float32
device: cpu
data: 
tensor([0., 0., 0.])


In [15]:
oten1=torch.ones(2,3)

print_info(oten1,'oten1')


[oten1]
shape: torch.Size([2, 3])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
oten2=torch.ones(3)

print_info(oten2,'oten2')


[oten2]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.float32
device: cpu
data: 
tensor([1., 1., 1.])


In [19]:
ften1=torch.full((3,),10)

print_info(ften1,'ften1')


[ften1]
shape: torch.Size([3])
ndim: 1차원
dtype: torch.int64
device: cpu
data: 
tensor([10, 10, 10])


In [20]:
ften2=torch.full((3,2),10)
print_info(ften2,'ften2')


[ften2]
shape: torch.Size([3, 2])
ndim: 2차원
dtype: torch.int64
device: cpu
data: 
tensor([[10, 10],
        [10, 10],
        [10, 10]])


In [21]:
eten1=torch.eye(3)

print_info(eten1,'eten1')


[eten1]
shape: torch.Size([3, 3])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [22]:
eten2=torch.eye(3,5)
print_info(eten2,'eten2')


[eten2]
shape: torch.Size([3, 5])
ndim: 2차원
dtype: torch.float32
device: cpu
data: 
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
